server:
  port: 8080
  servlet:
    context-path: /watch_aura
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/WATCH_AURA}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
    ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
jwt:
  signerKey: "PzcEXHkagVn34ElrlcOUQLazHeIg86xNVPk5Fj94TzH0RyCLngqSyPmzUtWc7yyP"
  expirationTime: 86400000
